server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid19-temp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
